DERP-251 - Create page section story and style the component as well …
GreaterLondonAuthority/gla_core_theme pull request #44
Opened 2021-09-08 16:03 UTC by Fullstack-Lincoln

…as the fix the home page header spacing

2021-09-08 16:07 UTC, joz-cti approved these changes

2021-09-09 10:13 UTC, philwolstenholme requested changes

2021-09-09 10:13 UTC, philwolstenholme commented on components/utilities.scss
> +
We can do this with Tailwind, we don't need to add new classes: https://tailwindcss.com/docs/screen-readers

2021-09-09 10:13 UTC, philwolstenholme commented on components/utilities.scss
> +
Example from the Tailwind docs:

```
<a href="#" class="sr-only focus:not-sr-only">
  Skip to content
</a>
```

2021-09-09 10:13 UTC, philwolstenholme commented on tailwind.config.js
> +    borderWidth: {
If we just want 1px let's add it to the `extend ` section rather than the `theme` section - that way we merge it with the Tailwind defaults rather than replacing the defaults.

2021-09-09 10:33 UTC, merged